# Generated by Django 5.2.7 on 2025-10-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ar_dashboard_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ARAgingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_1_30', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_31_60', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_61_90', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_91_120', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_120_plus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_invoices', models.IntegerField(default=0)),
                ('overdue_invoices', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aging_summary', to='ar_dashboard.customer')),
            ],
            options={
                'db_table': 'ar_dashboard_aragingsummary',
                'ordering': ['-total_outstanding'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ar_dashboard.customer')),
            ],
            options={
                'db_table': 'ar_dashboard_transaction',
                'ordering': ['-external_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('contact_id', models.CharField(db_index=True, max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('aging_bucket', models.CharField(blank=True, max_length=20, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='ar_dashboard.customer')),
            ],
            options={
                'db_table': 'ar_dashboard_invoice',
                'ordering': ['-invoice_at'],
                'indexes': [models.Index(fields=['due_at'], name='ar_dashboar_due_at_9af089_idx'), models.Index(fields=['status'], name='ar_dashboar_status_eea85a_idx'), models.Index(fields=['aging_bucket'], name='ar_dashboar_aging_b_7d050b_idx'), models.Index(fields=['contact_id'], name='ar_dashboar_contact_664425_idx')],
            },
        ),
    ]
