name: Deploy Dagster to Dagster Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip, wheel, setuptools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install dagster-cloud CLI
        run: |
          pip install dagster-cloud

      - name: Deploy to Dagster Cloud (serverless)
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
        run: |
          # run the serverless deploy; this uses your dagster_cloud.yaml
          dagster-cloud serverless deploy --non-interactive
